services:
  # integration-configs-redis
  - type: redis
    name: integration-configs-redis
    region: ohio
    ipAllowList: [] # only allow internal connections
  # integration-word-counter
  - type: web
    name: integration-word-counter
    region: ohio
    runtime: node
    rootDir: templates/word-counter
    buildCommand: npm i
    startCommand: npm run start
    buildFilter:
      paths:
        - templates/word-counter/**
    envVars:
      - key: REDIS_URL
        fromService:
          type: redis
          name: integration-configs-redis
          property: connectionString
  # integration-datacite-depositor
  - type: web
    name: integration-datacite-depositor
    region: ohio
    runtime: node
    rootDir: integrations/datacite-depositor
    buildCommand: npm i
    startCommand: npm run start
    buildFilter:
      paths:
        - templates/datacite-depositor/**
    envVars:
      - key: REDIS_URL
        fromService:
          type: redis
          name: integration-configs-redis
          property: connectionString
