# Based on https://docs.github.com/en/actions/deployment/deploying-to-your-cloud-provider/deploying-to-amazon-elastic-container-service

name: Promote from main

on:
  push:
    branches:
      - main
      - ships/fix-deploy-triggers

jobs:
  build-all:
    uses: ./.github/workflows/ecrbuild-all.yml
    secrets:
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}

  deploy-all:
    uses: ./.github/workflows/awsdeploy.yml
    environment: staging
    needs: build-all
    inputs:
      proper-name: blake
      environment: staging
    secrets:
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
